CREATE TABLE `erp_account` (
  `id` BIGINT AUTO_INCREMENT COMMENT "结算账户编号",
  `name` VARCHAR(255) COMMENT "账户名称",
  `no` VARCHAR(255) COMMENT "账户编码",
  `remark` VARCHAR(255) COMMENT "备注",
  `status` INT COMMENT "枚举 {@link enums.common.cn.nova.erp.framework.CommonStatusEnum}",
  `sort` INT COMMENT "排序",
  `default_status` BIT(1) COMMENT "是否默认",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 结算账户 DO";

CREATE TABLE `erp_finance_payment` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "付款单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `payment_time` DATETIME COMMENT "付款时间",
  `finance_user_id` BIGINT COMMENT "关联 AdminUserDO 的 id 字段",
  `supplier_id` BIGINT COMMENT "关联 {@link ErpSupplierDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `total_price` DECIMAL(24, 6) COMMENT "合计价格，单位：元",
  `discount_price` DECIMAL(24, 6) COMMENT "优惠金额，单位：元",
  `payment_price` DECIMAL(24, 6) COMMENT "paymentPrice = totalPrice - discountPrice",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 付款单 DO";

CREATE TABLE `erp_finance_payment_item` (
  `id` BIGINT AUTO_INCREMENT COMMENT "入库项编号",
  `payment_id` BIGINT COMMENT "关联 {@link ErpFinancePaymentDO#getId()}",
  `biz_type` INT COMMENT "枚举 {@link common.enums.cn.iocoder.yudao.module.erp.ErpBizTypeEnum} 的采购入库、退货",
  `biz_id` BIGINT COMMENT "例如说：{@link ErpPurchaseInDO#getId()}",
  `biz_no` VARCHAR(255) COMMENT "例如说：{@link ErpPurchaseInDO#getNo()}",
  `total_price` DECIMAL(24, 6) COMMENT "应付金额，单位：分",
  `paid_price` DECIMAL(24, 6) COMMENT "已付金额，单位：分",
  `payment_price` DECIMAL(24, 6) COMMENT "本次付款，单位：分",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 付款项 DO";

CREATE TABLE `erp_finance_receipt` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "收款单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `receipt_time` DATETIME COMMENT "收款时间",
  `finance_user_id` BIGINT COMMENT "关联 AdminUserDO 的 id 字段",
  `customer_id` BIGINT COMMENT "关联 {@link ErpCustomerDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `total_price` DECIMAL(24, 6) COMMENT "合计价格，单位：元",
  `discount_price` DECIMAL(24, 6) COMMENT "优惠金额，单位：元",
  `receipt_price` DECIMAL(24, 6) COMMENT "receiptPrice = totalPrice - discountPrice",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 收款单 DO";

CREATE TABLE `erp_finance_receipt_item` (
  `id` BIGINT AUTO_INCREMENT COMMENT "入库项编号",
  `receipt_id` BIGINT COMMENT "关联 {@link ErpFinanceReceiptDO#getId()}",
  `biz_type` INT COMMENT "枚举 {@link common.enums.cn.iocoder.yudao.module.erp.ErpBizTypeEnum} 的销售出库、退货",
  `biz_id` BIGINT COMMENT "例如说：{@link ErpSaleOutDO#getId()}",
  `biz_no` VARCHAR(255) COMMENT "例如说：{@link ErpSaleOutDO#getNo()}",
  `total_price` DECIMAL(24, 6) COMMENT "应收金额，单位：分",
  `receipted_price` DECIMAL(24, 6) COMMENT "已收金额，单位：分",
  `receipt_price` DECIMAL(24, 6) COMMENT "本次收款，单位：分",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 收款项 DO";

CREATE TABLE `erp_product_category` (
  `id` BIGINT AUTO_INCREMENT COMMENT "分类编号",
  `parent_id` BIGINT COMMENT "父分类编号",
  `name` VARCHAR(255) COMMENT "分类名称",
  `code` VARCHAR(255) COMMENT "分类编码",
  `sort` INT COMMENT "分类排序",
  `status` INT COMMENT "枚举 {@link enums.common.cn.nova.erp.framework.CommonStatusEnum}",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 产品分类 DO";

CREATE TABLE `erp_product` (
  `id` BIGINT AUTO_INCREMENT COMMENT "产品编号",
  `name` VARCHAR(255) COMMENT "产品名称",
  `bar_code` VARCHAR(255) COMMENT "产品条码",
  `category_id` BIGINT COMMENT "关联 {@link ErpProductCategoryDO#getId()}",
  `unit_id` BIGINT COMMENT "关联 {@link ErpProductUnitDO#getId()}",
  `status` INT COMMENT "枚举 {@link enums.common.cn.nova.erp.framework.CommonStatusEnum}",
  `standard` VARCHAR(255) COMMENT "产品规格",
  `remark` VARCHAR(255) COMMENT "产品备注",
  `expiry_day` INT COMMENT "保质期天数",
  `weight` DECIMAL(24, 6) COMMENT "基础重量（kg）",
  `purchase_price` DECIMAL(24, 6) COMMENT "采购价格，单位：元",
  `sale_price` DECIMAL(24, 6) COMMENT "销售价格，单位：元",
  `min_price` DECIMAL(24, 6) COMMENT "最低价格，单位：元",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 产品 DO";

CREATE TABLE `erp_product_unit` (
  `id` BIGINT AUTO_INCREMENT COMMENT "单位编号",
  `name` VARCHAR(255) COMMENT "单位名字",
  `status` INT COMMENT "单位状态",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 产品单位 DO";

CREATE TABLE `erppurchasein` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "采购入库单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `supplier_id` BIGINT COMMENT "关联 {@link ErpSupplierDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `in_time` DATETIME COMMENT "入库时间",
  `order_id` BIGINT COMMENT "关联 {@link ErpPurchaseOrderDO#getId()}",
  `order_no` VARCHAR(255) COMMENT "冗余 {@link ErpPurchaseOrderDO#getNo()}",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice",
  `payment_price` DECIMAL(24, 6) COMMENT "目的：和 {@link finance.dataobject.dal.cn.iocoder.yudao.module.erp.ErpFinancePaymentDO} 结合，记录已支付金额",
  `total_product_price` DECIMAL(24, 6) COMMENT "合计产品价格，单位：元",
  `total_tax_price` DECIMAL(24, 6) COMMENT "合计税额，单位：元",
  `discount_percent` DECIMAL(24, 6) COMMENT "优惠率，百分比",
  `discount_price` DECIMAL(24, 6) COMMENT "discountPercent",
  `other_price` DECIMAL(24, 6) COMMENT "其它金额，单位：元",
  `file_url` VARCHAR(255) COMMENT "附件地址",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 采购入库 DO";

CREATE TABLE `erp_purchase_in_items` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `in_id` BIGINT COMMENT "关联 {@link ErpPurchaseInDO##getId()}",
  `order_item_id` BIGINT COMMENT "目的：方便更新关联的采购订单项的入库数量",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单位单价，单位：元",
  `count` DECIMAL(24, 6) COMMENT "数量",
  `total_price` DECIMAL(24, 6) COMMENT "count",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率，百分比",
  `tax_price` DECIMAL(24, 6) COMMENT "taxPercent",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 采购入库项 DO";

CREATE TABLE `erppurchaseorder` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "采购订单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `supplier_id` BIGINT COMMENT "关联 {@link ErpSupplierDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `order_time` DATETIME COMMENT "下单时间",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "totalPrice = totalProductPrice + totalTaxPrice - discountPrice",
  `total_product_price` DECIMAL(24, 6) COMMENT "合计产品价格，单位：元",
  `total_tax_price` DECIMAL(24, 6) COMMENT "合计税额，单位：元",
  `discount_percent` DECIMAL(24, 6) COMMENT "优惠率，百分比",
  `discount_price` DECIMAL(24, 6) COMMENT "discountPercent",
  `deposit_price` DECIMAL(24, 6) COMMENT "定金金额，单位：元",
  `file_url` VARCHAR(255) COMMENT "附件地址",
  `remark` VARCHAR(255) COMMENT "备注",
  `in_count` DECIMAL(24, 6) COMMENT "采购入库数量",
  `return_count` DECIMAL(24, 6) COMMENT "采购退货数量",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 采购订单 DO";

CREATE TABLE `erp_purchase_order_items` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `order_id` BIGINT COMMENT "关联 {@link ErpPurchaseOrderDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单位单价，单位：元",
  `count` DECIMAL(24, 6) COMMENT "数量",
  `total_price` DECIMAL(24, 6) COMMENT "count",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率，百分比",
  `tax_price` DECIMAL(24, 6) COMMENT "taxPercent",
  `remark` VARCHAR(255) COMMENT "备注",
  `in_count` DECIMAL(24, 6) COMMENT "采购入库数量",
  `return_count` DECIMAL(24, 6) COMMENT "采购退货数量",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 采购订单项 DO";

CREATE TABLE `erppurchasereturn` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "采购退货单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `supplier_id` BIGINT COMMENT "关联 {@link ErpSupplierDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `return_time` DATETIME COMMENT "退货时间",
  `order_id` BIGINT COMMENT "关联 {@link ErpPurchaseOrderDO#getId()}",
  `order_no` VARCHAR(255) COMMENT "冗余 {@link ErpPurchaseOrderDO#getNo()}",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice",
  `refund_price` DECIMAL(24, 6) COMMENT "目的：和 {@link finance.dataobject.dal.cn.iocoder.yudao.module.erp.ErpFinancePaymentDO} 结合，记录已支付金额",
  `total_product_price` DECIMAL(24, 6) COMMENT "合计产品价格，单位：元",
  `total_tax_price` DECIMAL(24, 6) COMMENT "合计税额，单位：元",
  `discount_percent` DECIMAL(24, 6) COMMENT "优惠率，百分比",
  `discount_price` DECIMAL(24, 6) COMMENT "discountPercent",
  `other_price` DECIMAL(24, 6) COMMENT "其它金额，单位：元",
  `file_url` VARCHAR(255) COMMENT "附件地址",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 采购退货 DO";

CREATE TABLE `erp_purchase_return_items` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `return_id` BIGINT COMMENT "关联 {@link ErpPurchaseReturnDO##getId()}",
  `order_item_id` BIGINT COMMENT "目的：方便更新关联的采购订单项的退货数量",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单位单价，单位：元",
  `count` DECIMAL(24, 6) COMMENT "数量",
  `total_price` DECIMAL(24, 6) COMMENT "count",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率，百分比",
  `tax_price` DECIMAL(24, 6) COMMENT "taxPercent",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 采购退货项 DO";

CREATE TABLE `erp_supplier` (
  `id` BIGINT AUTO_INCREMENT COMMENT "供应商编号",
  `name` VARCHAR(255) COMMENT "供应商名称",
  `contact` VARCHAR(255) COMMENT "联系人",
  `mobile` VARCHAR(255) COMMENT "手机号码",
  `telephone` VARCHAR(255) COMMENT "联系电话",
  `email` VARCHAR(255) COMMENT "电子邮箱",
  `fax` VARCHAR(255) COMMENT "传真",
  `remark` VARCHAR(255) COMMENT "备注",
  `status` INT COMMENT "枚举 {@link enums.common.cn.nova.erp.framework.CommonStatusEnum}",
  `sort` INT COMMENT "排序",
  `tax_no` VARCHAR(255) COMMENT "纳税人识别号",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率",
  `bank_name` VARCHAR(255) COMMENT "开户行",
  `bank_account` VARCHAR(255) COMMENT "开户账号",
  `bank_address` VARCHAR(255) COMMENT "开户地址",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 供应商 DO";

CREATE TABLE `erp_customer` (
  `id` BIGINT AUTO_INCREMENT COMMENT "客户编号",
  `name` VARCHAR(255) COMMENT "客户名称",
  `contact` VARCHAR(255) COMMENT "联系人",
  `mobile` VARCHAR(255) COMMENT "手机号码",
  `telephone` VARCHAR(255) COMMENT "联系电话",
  `email` VARCHAR(255) COMMENT "电子邮箱",
  `fax` VARCHAR(255) COMMENT "传真",
  `remark` VARCHAR(255) COMMENT "备注",
  `status` INT COMMENT "枚举 {@link enums.common.cn.nova.erp.framework.CommonStatusEnum}",
  `sort` INT COMMENT "排序",
  `tax_no` VARCHAR(255) COMMENT "纳税人识别号",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率",
  `bank_name` VARCHAR(255) COMMENT "开户行",
  `bank_account` VARCHAR(255) COMMENT "开户账号",
  `bank_address` VARCHAR(255) COMMENT "开户地址",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 客户 DO";

CREATE TABLE `erpsaleorder` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "销售订单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `customer_id` BIGINT COMMENT "关联 {@link ErpCustomerDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `sale_user_id` BIGINT COMMENT "关联 AdminUserDO 的 id 字段",
  `order_time` DATETIME COMMENT "下单时间",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "totalPrice = totalProductPrice + totalTaxPrice - discountPrice",
  `total_product_price` DECIMAL(24, 6) COMMENT "合计产品价格，单位：元",
  `total_tax_price` DECIMAL(24, 6) COMMENT "合计税额，单位：元",
  `discount_percent` DECIMAL(24, 6) COMMENT "优惠率，百分比",
  `discount_price` DECIMAL(24, 6) COMMENT "discountPercent",
  `deposit_price` DECIMAL(24, 6) COMMENT "定金金额，单位：元",
  `file_url` VARCHAR(255) COMMENT "附件地址",
  `remark` VARCHAR(255) COMMENT "备注",
  `out_count` DECIMAL(24, 6) COMMENT "销售出库数量",
  `return_count` DECIMAL(24, 6) COMMENT "销售退货数量",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 销售订单 DO";

CREATE TABLE `erp_sale_order_items` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `order_id` BIGINT COMMENT "关联 {@link ErpSaleOrderDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单位单价，单位：元",
  `count` DECIMAL(24, 6) COMMENT "数量",
  `total_price` DECIMAL(24, 6) COMMENT "count",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率，百分比",
  `tax_price` DECIMAL(24, 6) COMMENT "taxPercent",
  `remark` VARCHAR(255) COMMENT "备注",
  `out_count` DECIMAL(24, 6) COMMENT "销售出库数量",
  `return_count` DECIMAL(24, 6) COMMENT "销售退货数量",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 销售订单项 DO";

CREATE TABLE `erpsaleout` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "销售出库单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `customer_id` BIGINT COMMENT "关联 {@link ErpCustomerDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `sale_user_id` BIGINT COMMENT "关联 AdminUserDO 的 id 字段",
  `out_time` DATETIME COMMENT "出库时间",
  `order_id` BIGINT COMMENT "关联 {@link ErpSaleOrderDO#getId()}",
  `order_no` VARCHAR(255) COMMENT "冗余 {@link ErpSaleOrderDO#getNo()}",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice",
  `receipt_price` DECIMAL(24, 6) COMMENT "目的：和 {@link finance.dataobject.dal.cn.iocoder.yudao.module.erp.ErpFinanceReceiptDO} 结合，记录已收款金额",
  `total_product_price` DECIMAL(24, 6) COMMENT "合计产品价格，单位：元",
  `total_tax_price` DECIMAL(24, 6) COMMENT "合计税额，单位：元",
  `discount_percent` DECIMAL(24, 6) COMMENT "优惠率，百分比",
  `discount_price` DECIMAL(24, 6) COMMENT "discountPercent",
  `other_price` DECIMAL(24, 6) COMMENT "其它金额，单位：元",
  `file_url` VARCHAR(255) COMMENT "附件地址",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 销售出库 DO";

CREATE TABLE `erp_sale_out_items` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `out_id` BIGINT COMMENT "关联 {@link ErpStockOutDO##getId()}",
  `order_item_id` BIGINT COMMENT "目的：方便更新关联的销售订单项的出库数量",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单位单价，单位：元",
  `count` DECIMAL(24, 6) COMMENT "数量",
  `total_price` DECIMAL(24, 6) COMMENT "count",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率，百分比",
  `tax_price` DECIMAL(24, 6) COMMENT "taxPercent",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 销售出库项 DO";

CREATE TABLE `erpsalereturn` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `no` VARCHAR(255) COMMENT "销售退货单号",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `customer_id` BIGINT COMMENT "关联 {@link ErpCustomerDO#getId()}",
  `account_id` BIGINT COMMENT "关联 {@link ErpAccountDO#getId()}",
  `sale_user_id` BIGINT COMMENT "关联 AdminUserDO 的 id 字段",
  `return_time` DATETIME COMMENT "退货时间",
  `order_id` BIGINT COMMENT "关联 {@link ErpSaleOrderDO#getId()}",
  `order_no` VARCHAR(255) COMMENT "冗余 {@link ErpSaleOrderDO#getNo()}",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "totalPrice = totalProductPrice + totalTaxPrice - discountPrice + otherPrice",
  `refund_price` DECIMAL(24, 6) COMMENT "目的：和 {@link finance.dataobject.dal.cn.iocoder.yudao.module.erp.ErpFinanceReceiptDO} 结合，记录已退款金额",
  `total_product_price` DECIMAL(24, 6) COMMENT "合计产品价格，单位：元",
  `total_tax_price` DECIMAL(24, 6) COMMENT "合计税额，单位：元",
  `discount_percent` DECIMAL(24, 6) COMMENT "优惠率，百分比",
  `discount_price` DECIMAL(24, 6) COMMENT "discountPercent",
  `other_price` DECIMAL(24, 6) COMMENT "其它金额，单位：元",
  `file_url` VARCHAR(255) COMMENT "附件地址",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 销售退货 DO";

CREATE TABLE `erp_sale_return_items` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `return_id` BIGINT COMMENT "关联 {@link ErpSaleReturnDO##getId()}",
  `order_item_id` BIGINT COMMENT "目的：方便更新关联的销售订单项的退货数量",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单位单价，单位：元",
  `count` DECIMAL(24, 6) COMMENT "数量",
  `total_price` DECIMAL(24, 6) COMMENT "count",
  `tax_percent` DECIMAL(24, 6) COMMENT "税率，百分比",
  `tax_price` DECIMAL(24, 6) COMMENT "taxPercent",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 销售退货项 DO";

CREATE TABLE `erp_stock_check` (
  `id` BIGINT AUTO_INCREMENT COMMENT "盘点编号",
  `no` VARCHAR(255) COMMENT "盘点单号",
  `check_time` DATETIME COMMENT "盘点时间",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `remark` VARCHAR(255) COMMENT "备注",
  `file_url` VARCHAR(255) COMMENT "附件 URL",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 库存盘点单 DO";

CREATE TABLE `erp_stock_check_item` (
  `id` BIGINT AUTO_INCREMENT COMMENT "盘点项编号",
  `check_id` BIGINT COMMENT "关联 {@link ErpStockCheckDO#getId()}",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单价",
  `stock_count` DECIMAL(24, 6) COMMENT "账面数量（当前库存）",
  `actual_count` DECIMAL(24, 6) COMMENT "实际数量（实际库存）",
  `count` DECIMAL(24, 6) COMMENT "count = stockCount - actualCount",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 库存盘点单项 DO";

CREATE TABLE `erp_stock` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `count` DECIMAL(24, 6) COMMENT "库存数量",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 产品库存 DO";

CREATE TABLE `erp_stock_in` (
  `id` BIGINT AUTO_INCREMENT COMMENT "入库编号",
  `no` VARCHAR(255) COMMENT "入库单号",
  `supplier_id` BIGINT COMMENT "关联 {@link ErpSupplierDO#getId()}",
  `in_time` DATETIME COMMENT "入库时间",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `remark` VARCHAR(255) COMMENT "备注",
  `file_url` VARCHAR(255) COMMENT "附件 URL",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 其它入库单 DO";

CREATE TABLE `erp_stock_in_item` (
  `id` BIGINT AUTO_INCREMENT COMMENT "入库项编号",
  `in_id` BIGINT COMMENT "关联 {@link ErpStockInDO#getId()}",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单价",
  `count` DECIMAL(24, 6) COMMENT "产品数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 其它入库单项 DO";

CREATE TABLE `erp_stock_move` (
  `id` BIGINT AUTO_INCREMENT COMMENT "调拨编号",
  `no` VARCHAR(255) COMMENT "调拨单号",
  `move_time` DATETIME COMMENT "调拨时间",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `remark` VARCHAR(255) COMMENT "备注",
  `file_url` VARCHAR(255) COMMENT "附件 URL",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 库存调拨单 DO";

CREATE TABLE `erp_stock_move_item` (
  `id` BIGINT AUTO_INCREMENT COMMENT "调拨项编号",
  `move_id` BIGINT COMMENT "关联 {@link ErpStockMoveDO#getId()}",
  `from_warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `to_warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单价",
  `count` DECIMAL(24, 6) COMMENT "产品数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 库存调拨单项 DO";

CREATE TABLE `erp_stock_out` (
  `id` BIGINT AUTO_INCREMENT COMMENT "出库编号",
  `no` VARCHAR(255) COMMENT "出库单号",
  `customer_id` BIGINT COMMENT "TODO 芋艿：待关联",
  `out_time` DATETIME COMMENT "出库时间",
  `total_count` DECIMAL(24, 6) COMMENT "合计数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `status` INT COMMENT "枚举 {@link enums.cn.iocoder.yudao.module.erp.ErpAuditStatus}",
  `remark` VARCHAR(255) COMMENT "备注",
  `file_url` VARCHAR(255) COMMENT "附件 URL",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 其它出库单 DO";

CREATE TABLE `erp_stock_out_item` (
  `id` BIGINT AUTO_INCREMENT COMMENT "出库项编号",
  `out_id` BIGINT COMMENT "关联 {@link ErpStockOutDO#getId()}",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `product_unit_id` BIGINT COMMENT "冗余 {@link ErpProductDO#getUnitId()}",
  `product_price` DECIMAL(24, 6) COMMENT "产品单价",
  `count` DECIMAL(24, 6) COMMENT "产品数量",
  `total_price` DECIMAL(24, 6) COMMENT "合计金额，单位：元",
  `remark` VARCHAR(255) COMMENT "备注",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 其它出库单项 DO";

CREATE TABLE `erp_stock_record` (
  `id` BIGINT AUTO_INCREMENT COMMENT "编号",
  `product_id` BIGINT COMMENT "关联 {@link ErpProductDO#getId()}",
  `warehouse_id` BIGINT COMMENT "关联 {@link ErpWarehouseDO#getId()}",
  `count` DECIMAL(24, 6) COMMENT "正数，表示入库；负数，表示出库",
  `total_count` DECIMAL(24, 6) COMMENT "出入库之后，目前的库存量",
  `biz_type` INT COMMENT "枚举 {@link ErpStockRecordBizTypeEnum}",
  `biz_id` BIGINT COMMENT "例如说：{@link ErpStockInDO#getId()}",
  `biz_item_id` BIGINT COMMENT "例如说：{@link ErpStockInItemDO#getId()}",
  `biz_no` VARCHAR(255) COMMENT "例如说：{@link ErpStockInDO#getNo()}",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 产品库存明细 DO";

CREATE TABLE `erp_warehouse` (
  `id` BIGINT AUTO_INCREMENT COMMENT "仓库编号",
  `name` VARCHAR(255) COMMENT "仓库名称",
  `address` VARCHAR(255) COMMENT "仓库地址",
  `sort` BIGINT COMMENT "排序",
  `remark` VARCHAR(255) COMMENT "备注",
  `principal` VARCHAR(255) COMMENT "负责人",
  `warehouse_price` DECIMAL(24, 6) COMMENT "仓储费，单位：元",
  `truckage_price` DECIMAL(24, 6) COMMENT "搬运费，单位：元",
  `status` INT COMMENT "枚举 {@link enums.common.cn.nova.erp.framework.CommonStatusEnum}",
  `default_status` BIT(1) COMMENT "是否默认",
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`)
) COMMENT="ERP 仓库 DO";
